### ISSUE TITLE
Error: Exited with code 2 on yarn start:dev command

### ISSUE THREAD

**Issue by alfonsocatanzaro** [s-h-a-d-o-w/rhl-electron-quick-start#1]
Hi,
I have this error when I launch "yarn start:dev" command:
```
An error occurred:  Error: Exited with code 2
    at ChildProcess.<anonymous> (C:\github.com\rhl-electron-quick-start\node_modules\cross-unzip\index.js:42:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
With some `console.log` in `node_modules\cross-unzip\index.js:` I reached to the real command that it tries to launch

`C:\github.com\rhl-electron-quick-start\node_modules\7zip\7zip-lite\7z.exe x "C:\\Users\\alfon\\AppData\\Roaming\\rhl-electron-quick-start\\extensions\\fmkadmapgofadopljbjfkapdkoienihi.crx" -y -o"C:\\Users\\alfon\\AppData\\Roaming\\rhl-electron-quick-start\\extensions\\fmkadmapgofadopljbjfkapdkoienihi"
`
and this is what I obtain: 
```
7-Zip [64] 15.05 beta : Copyright (c) 1999-2015 Igor Pavlov : 2015-06-14

Scanning the drive for archives:
1 file, 0 bytes

Extracting archive: C:\Users\alfon\AppData\Roaming\rhl-electron-quick-start\extensions\fmkadmapgofadopljbjfkapdkoienihi.crx
ERROR: C:\Users\alfon\AppData\Roaming\rhl-electron-quick-start\extensions\fmkadmapgofadopljbjfkapdkoienihi.crx
Can not open the file as archive


Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```
The problem is that file fmkadmapgofadopljbjfkapdkoienihi.crx is empty (0 bytes).
I'm using node v12.19.0.
I have same error on mac os.
Thank you for help.
Alfonso.

**Comment by s-h-a-d-o-w** [comment]
Thank you very much for your report and apologies for the delayed response. I haven't used Electron in years, so this didn't have high priority...

That said, I've just now updated all dependencies and configs and now it works fine again. :)

Could you please confirm and close the issue if it works for you as well?

**Comment by s-h-a-d-o-w** [comment]
I just realized that React Hot Loader got deprecated.
Will archive this project and recommend using e.g. [this](https://github.com/electron-react-boilerplate/electron-react-boilerplate) instead.
